FROM python:3.12-slim-bookworm as base
WORKDIR /usr/src/app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update && apt-get install -y git && apt-get clean

RUN git clone -b feat/anon-creds https://github.com/Indicio-tech/acapy-did-indy.git
WORKDIR /usr/src/app/acapy-did-indy

RUN uv sync --all-extras

ENTRYPOINT ["uv", "run", "fastapi", "dev", "src/did_web_server/__init__.py"]
CMD ["--host", "0.0.0.0", "--port", "8000"]