inbound-transport:
  - [http, 0.0.0.0, 3000]
label: Bob
outbound-transport: http
endpoint: http://bob:3000
admin: [0.0.0.0, 3001]
admin-insecure-mode: true
log-level: debug
webhook-url: http://echo:3002/webhook
genesis-url: https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
wallet-type: indy
wallet-name: bob
wallet-key: insecure
auto-provision: true
