name: Code Quality Check

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@24.1.1
        with:
          src: "./acapy_controller ./examples"
      - uses: chartboost/ruff-action@v1
        with:
          src: "./acapy_controller ./examples"
