name: Publish
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Confidence check (run tests)
        run: |
          docker-compose run tests
      - name: Build package
        run: |
          poetry build
      - name: Publish package
        run: |
          poetry publish
