# Authored by Alexandra N. Walker <alex.walker@indicio.tech> ☀️

name: tests
"on":
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      - feature/**
      - feat/**

env:
  POETRY_VERSION: 1.1.11

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test with docker-compose
      run: |
        docker-compose run tests
